/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRouteImport } from './routes/$owner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RepoOwnerRepoRouteImport } from './routes/repo.$owner.$repo'
import { Route as ApiIntegrationsV1CapabilitiesRouteImport } from './routes/api.integrations.v1.capabilities'
import { Route as ApiIntegrationsV1EventsRouteImport } from './routes/api.integrations.v1.events'
import { Route as ApiIntegrationsV1RepositoriesRouteImport } from './routes/api.integrations.v1.repositories'
import { Route as RepoOwnerRepoIssuesRouteImport } from './routes/repo.$owner.$repo.issues'
import { Route as RepoOwnerRepoPullsRouteImport } from './routes/repo.$owner.$repo.pulls'
import { Route as RepoOwnerRepoSettingsRouteImport } from './routes/repo.$owner.$repo.settings'
import { Route as RepoOwnerRepoIssuesNumberRouteImport } from './routes/repo.$owner.$repo.issues.$number'
import { Route as RepoOwnerRepoPullsNumberRouteImport } from './routes/repo.$owner.$repo.pulls.$number'
import { Route as RepoOwnerRepoPullsNewRouteImport } from './routes/repo.$owner.$repo.pulls.new'
import { Route as ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRouteImport } from './routes/api.integrations.v1.repositories.$owner.$repo.snapshots.$revision'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/$owner',
  path: '/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoOwnerRepoRoute = RepoOwnerRepoRouteImport.update({
  id: '/repo/$owner/$repo',
  path: '/repo/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsV1CapabilitiesRoute =
  ApiIntegrationsV1CapabilitiesRouteImport.update({
    id: '/api/integrations/v1/capabilities',
    path: '/api/integrations/v1/capabilities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsV1EventsRoute = ApiIntegrationsV1EventsRouteImport.update({
  id: '/api/integrations/v1/events',
  path: '/api/integrations/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsV1RepositoriesRoute =
  ApiIntegrationsV1RepositoriesRouteImport.update({
    id: '/api/integrations/v1/repositories',
    path: '/api/integrations/v1/repositories',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepoOwnerRepoIssuesRoute = RepoOwnerRepoIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => RepoOwnerRepoRoute,
} as any)
const RepoOwnerRepoPullsRoute = RepoOwnerRepoPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => RepoOwnerRepoRoute,
} as any)
const RepoOwnerRepoSettingsRoute = RepoOwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RepoOwnerRepoRoute,
} as any)
const RepoOwnerRepoIssuesNumberRoute =
  RepoOwnerRepoIssuesNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => RepoOwnerRepoIssuesRoute,
  } as any)
const RepoOwnerRepoPullsNumberRoute =
  RepoOwnerRepoPullsNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => RepoOwnerRepoPullsRoute,
  } as any)
const RepoOwnerRepoPullsNewRoute = RepoOwnerRepoPullsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RepoOwnerRepoPullsRoute,
} as any)
const ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRoute =
  ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRouteImport.update({
    id: '/$owner/$repo/snapshots/$revision',
    path: '/$owner/$repo/snapshots/$revision',
    getParentRoute: () => ApiIntegrationsV1RepositoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$owner': typeof OwnerRoute
  '/settings': typeof SettingsRoute
  '/repo/$owner/$repo': typeof RepoOwnerRepoRouteWithChildren
  '/api/integrations/v1/capabilities': typeof ApiIntegrationsV1CapabilitiesRoute
  '/api/integrations/v1/events': typeof ApiIntegrationsV1EventsRoute
  '/api/integrations/v1/repositories': typeof ApiIntegrationsV1RepositoriesRouteWithChildren
  '/repo/$owner/$repo/issues': typeof RepoOwnerRepoIssuesRouteWithChildren
  '/repo/$owner/$repo/pulls': typeof RepoOwnerRepoPullsRouteWithChildren
  '/repo/$owner/$repo/settings': typeof RepoOwnerRepoSettingsRoute
  '/repo/$owner/$repo/issues/$number': typeof RepoOwnerRepoIssuesNumberRoute
  '/repo/$owner/$repo/pulls/$number': typeof RepoOwnerRepoPullsNumberRoute
  '/repo/$owner/$repo/pulls/new': typeof RepoOwnerRepoPullsNewRoute
  '/api/integrations/v1/repositories/$owner/$repo/snapshots/$revision': typeof ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$owner': typeof OwnerRoute
  '/settings': typeof SettingsRoute
  '/repo/$owner/$repo': typeof RepoOwnerRepoRouteWithChildren
  '/api/integrations/v1/capabilities': typeof ApiIntegrationsV1CapabilitiesRoute
  '/api/integrations/v1/events': typeof ApiIntegrationsV1EventsRoute
  '/api/integrations/v1/repositories': typeof ApiIntegrationsV1RepositoriesRouteWithChildren
  '/repo/$owner/$repo/issues': typeof RepoOwnerRepoIssuesRouteWithChildren
  '/repo/$owner/$repo/pulls': typeof RepoOwnerRepoPullsRouteWithChildren
  '/repo/$owner/$repo/settings': typeof RepoOwnerRepoSettingsRoute
  '/repo/$owner/$repo/issues/$number': typeof RepoOwnerRepoIssuesNumberRoute
  '/repo/$owner/$repo/pulls/$number': typeof RepoOwnerRepoPullsNumberRoute
  '/repo/$owner/$repo/pulls/new': typeof RepoOwnerRepoPullsNewRoute
  '/api/integrations/v1/repositories/$owner/$repo/snapshots/$revision': typeof ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$owner': typeof OwnerRoute
  '/settings': typeof SettingsRoute
  '/repo/$owner/$repo': typeof RepoOwnerRepoRouteWithChildren
  '/api/integrations/v1/capabilities': typeof ApiIntegrationsV1CapabilitiesRoute
  '/api/integrations/v1/events': typeof ApiIntegrationsV1EventsRoute
  '/api/integrations/v1/repositories': typeof ApiIntegrationsV1RepositoriesRouteWithChildren
  '/repo/$owner/$repo/issues': typeof RepoOwnerRepoIssuesRouteWithChildren
  '/repo/$owner/$repo/pulls': typeof RepoOwnerRepoPullsRouteWithChildren
  '/repo/$owner/$repo/settings': typeof RepoOwnerRepoSettingsRoute
  '/repo/$owner/$repo/issues/$number': typeof RepoOwnerRepoIssuesNumberRoute
  '/repo/$owner/$repo/pulls/$number': typeof RepoOwnerRepoPullsNumberRoute
  '/repo/$owner/$repo/pulls/new': typeof RepoOwnerRepoPullsNewRoute
  '/api/integrations/v1/repositories/$owner/$repo/snapshots/$revision': typeof ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$owner'
    | '/settings'
    | '/repo/$owner/$repo'
    | '/api/integrations/v1/capabilities'
    | '/api/integrations/v1/events'
    | '/api/integrations/v1/repositories'
    | '/repo/$owner/$repo/issues'
    | '/repo/$owner/$repo/pulls'
    | '/repo/$owner/$repo/settings'
    | '/repo/$owner/$repo/issues/$number'
    | '/repo/$owner/$repo/pulls/$number'
    | '/repo/$owner/$repo/pulls/new'
    | '/api/integrations/v1/repositories/$owner/$repo/snapshots/$revision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$owner'
    | '/settings'
    | '/repo/$owner/$repo'
    | '/api/integrations/v1/capabilities'
    | '/api/integrations/v1/events'
    | '/api/integrations/v1/repositories'
    | '/repo/$owner/$repo/issues'
    | '/repo/$owner/$repo/pulls'
    | '/repo/$owner/$repo/settings'
    | '/repo/$owner/$repo/issues/$number'
    | '/repo/$owner/$repo/pulls/$number'
    | '/repo/$owner/$repo/pulls/new'
    | '/api/integrations/v1/repositories/$owner/$repo/snapshots/$revision'
  id:
    | '__root__'
    | '/'
    | '/$owner'
    | '/settings'
    | '/repo/$owner/$repo'
    | '/api/integrations/v1/capabilities'
    | '/api/integrations/v1/events'
    | '/api/integrations/v1/repositories'
    | '/repo/$owner/$repo/issues'
    | '/repo/$owner/$repo/pulls'
    | '/repo/$owner/$repo/settings'
    | '/repo/$owner/$repo/issues/$number'
    | '/repo/$owner/$repo/pulls/$number'
    | '/repo/$owner/$repo/pulls/new'
    | '/api/integrations/v1/repositories/$owner/$repo/snapshots/$revision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRoute
  SettingsRoute: typeof SettingsRoute
  RepoOwnerRepoRoute: typeof RepoOwnerRepoRouteWithChildren
  ApiIntegrationsV1CapabilitiesRoute: typeof ApiIntegrationsV1CapabilitiesRoute
  ApiIntegrationsV1EventsRoute: typeof ApiIntegrationsV1EventsRoute
  ApiIntegrationsV1RepositoriesRoute: typeof ApiIntegrationsV1RepositoriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner': {
      id: '/$owner'
      path: '/$owner'
      fullPath: '/$owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$owner/$repo': {
      id: '/repo/$owner/$repo'
      path: '/repo/$owner/$repo'
      fullPath: '/repo/$owner/$repo'
      preLoaderRoute: typeof RepoOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/v1/capabilities': {
      id: '/api/integrations/v1/capabilities'
      path: '/api/integrations/v1/capabilities'
      fullPath: '/api/integrations/v1/capabilities'
      preLoaderRoute: typeof ApiIntegrationsV1CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/v1/events': {
      id: '/api/integrations/v1/events'
      path: '/api/integrations/v1/events'
      fullPath: '/api/integrations/v1/events'
      preLoaderRoute: typeof ApiIntegrationsV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/v1/repositories': {
      id: '/api/integrations/v1/repositories'
      path: '/api/integrations/v1/repositories'
      fullPath: '/api/integrations/v1/repositories'
      preLoaderRoute: typeof ApiIntegrationsV1RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$owner/$repo/issues': {
      id: '/repo/$owner/$repo/issues'
      path: '/issues'
      fullPath: '/repo/$owner/$repo/issues'
      preLoaderRoute: typeof RepoOwnerRepoIssuesRouteImport
      parentRoute: typeof RepoOwnerRepoRoute
    }
    '/repo/$owner/$repo/pulls': {
      id: '/repo/$owner/$repo/pulls'
      path: '/pulls'
      fullPath: '/repo/$owner/$repo/pulls'
      preLoaderRoute: typeof RepoOwnerRepoPullsRouteImport
      parentRoute: typeof RepoOwnerRepoRoute
    }
    '/repo/$owner/$repo/settings': {
      id: '/repo/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/repo/$owner/$repo/settings'
      preLoaderRoute: typeof RepoOwnerRepoSettingsRouteImport
      parentRoute: typeof RepoOwnerRepoRoute
    }
    '/repo/$owner/$repo/issues/$number': {
      id: '/repo/$owner/$repo/issues/$number'
      path: '/$number'
      fullPath: '/repo/$owner/$repo/issues/$number'
      preLoaderRoute: typeof RepoOwnerRepoIssuesNumberRouteImport
      parentRoute: typeof RepoOwnerRepoIssuesRoute
    }
    '/repo/$owner/$repo/pulls/$number': {
      id: '/repo/$owner/$repo/pulls/$number'
      path: '/$number'
      fullPath: '/repo/$owner/$repo/pulls/$number'
      preLoaderRoute: typeof RepoOwnerRepoPullsNumberRouteImport
      parentRoute: typeof RepoOwnerRepoPullsRoute
    }
    '/repo/$owner/$repo/pulls/new': {
      id: '/repo/$owner/$repo/pulls/new'
      path: '/new'
      fullPath: '/repo/$owner/$repo/pulls/new'
      preLoaderRoute: typeof RepoOwnerRepoPullsNewRouteImport
      parentRoute: typeof RepoOwnerRepoPullsRoute
    }
    '/api/integrations/v1/repositories/$owner/$repo/snapshots/$revision': {
      id: '/api/integrations/v1/repositories/$owner/$repo/snapshots/$revision'
      path: '/$owner/$repo/snapshots/$revision'
      fullPath: '/api/integrations/v1/repositories/$owner/$repo/snapshots/$revision'
      preLoaderRoute: typeof ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRouteImport
      parentRoute: typeof ApiIntegrationsV1RepositoriesRoute
    }
  }
}

interface RepoOwnerRepoIssuesRouteChildren {
  RepoOwnerRepoIssuesNumberRoute: typeof RepoOwnerRepoIssuesNumberRoute
}

const RepoOwnerRepoIssuesRouteChildren: RepoOwnerRepoIssuesRouteChildren = {
  RepoOwnerRepoIssuesNumberRoute: RepoOwnerRepoIssuesNumberRoute,
}

const RepoOwnerRepoIssuesRouteWithChildren =
  RepoOwnerRepoIssuesRoute._addFileChildren(RepoOwnerRepoIssuesRouteChildren)

interface RepoOwnerRepoPullsRouteChildren {
  RepoOwnerRepoPullsNumberRoute: typeof RepoOwnerRepoPullsNumberRoute
  RepoOwnerRepoPullsNewRoute: typeof RepoOwnerRepoPullsNewRoute
}

const RepoOwnerRepoPullsRouteChildren: RepoOwnerRepoPullsRouteChildren = {
  RepoOwnerRepoPullsNumberRoute: RepoOwnerRepoPullsNumberRoute,
  RepoOwnerRepoPullsNewRoute: RepoOwnerRepoPullsNewRoute,
}

const RepoOwnerRepoPullsRouteWithChildren =
  RepoOwnerRepoPullsRoute._addFileChildren(RepoOwnerRepoPullsRouteChildren)

interface RepoOwnerRepoRouteChildren {
  RepoOwnerRepoIssuesRoute: typeof RepoOwnerRepoIssuesRouteWithChildren
  RepoOwnerRepoPullsRoute: typeof RepoOwnerRepoPullsRouteWithChildren
  RepoOwnerRepoSettingsRoute: typeof RepoOwnerRepoSettingsRoute
}

const RepoOwnerRepoRouteChildren: RepoOwnerRepoRouteChildren = {
  RepoOwnerRepoIssuesRoute: RepoOwnerRepoIssuesRouteWithChildren,
  RepoOwnerRepoPullsRoute: RepoOwnerRepoPullsRouteWithChildren,
  RepoOwnerRepoSettingsRoute: RepoOwnerRepoSettingsRoute,
}

const RepoOwnerRepoRouteWithChildren = RepoOwnerRepoRoute._addFileChildren(
  RepoOwnerRepoRouteChildren,
)

interface ApiIntegrationsV1RepositoriesRouteChildren {
  ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRoute: typeof ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRoute
}

const ApiIntegrationsV1RepositoriesRouteChildren: ApiIntegrationsV1RepositoriesRouteChildren =
  {
    ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRoute:
      ApiIntegrationsV1RepositoriesOwnerRepoSnapshotsRevisionRoute,
  }

const ApiIntegrationsV1RepositoriesRouteWithChildren =
  ApiIntegrationsV1RepositoriesRoute._addFileChildren(
    ApiIntegrationsV1RepositoriesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRoute,
  SettingsRoute: SettingsRoute,
  RepoOwnerRepoRoute: RepoOwnerRepoRouteWithChildren,
  ApiIntegrationsV1CapabilitiesRoute: ApiIntegrationsV1CapabilitiesRoute,
  ApiIntegrationsV1EventsRoute: ApiIntegrationsV1EventsRoute,
  ApiIntegrationsV1RepositoriesRoute:
    ApiIntegrationsV1RepositoriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
